translations = {
    'en': {
        'greeting': "👋 Hello, {user_name}! I'm a movie search bot. Choose an action:",
        'random_movie': "🎥 *Random Movie:* `{movie}`",
        'actor_search': "🎭 *Movies with {actor_name}:* \n{movies}",
        'genre_search': "🎭 *Movies of genre {genre_name}:* \n{movies}",
        'year_search': "📅 *Movies from {year}:* \n{movies}",
        'popular_queries': "📊 *Popular Queries:* \n{queries}",
        'enter_actor_name': "✍ Enter the actor's name to search:",
        'enter_genre_name': "✍ Enter the genre to search:",
        'enter_year': "✍ Enter the year to search:",
        'error': "🚨 Error connecting to the database.",
        'no_results': "😔 No results found.",
        'random_movie_button': '🎲 Random Movie',
        'search_actor_button': '🔎 Search by Actor',
        'search_genre_button': '🎭 Search by Genre',
        'search_year_button': '📅 Search by Year',
        'popular_queries_button': '📊 Popular Queries',
        'change_language_button': '🌐 Change Language',
    },
    'ru': {
        'greeting': "👋 Привет, {user_name}! Я бот для поиска фильмов. Выберите действие:",
        'random_movie': "🎥 *Случайный фильм:* `{movie}`",
        'actor_search': "🎭 *Фильмы с {actor_name}:* \n{movies}",
        'genre_search': "🎭 *Фильмы жанра {genre_name}:* \n{movies}",
        'year_search': "📅 *Фильмы {year} года:* \n{movies}",
        'popular_queries': "📊 *Популярные запросы:* \n{queries}",
        'enter_actor_name': "✍ Введите имя актера для поиска:",
        'enter_genre_name': "✍ Введите жанр для поиска:",
        'enter_year': "✍ Введите год для поиска:",
        'error': "🚨 Ошибка подключения к базе данных.",
        'no_results': "😔 Результаты не найдены.",
        'random_movie_button': '🎲 Случайный фильм',
        'search_actor_button': '🔎 Поиск по актеру',
        'search_genre_button': '🎭 Поиск по жанру',
        'search_year_button': '📅 Поиск по году',
        'popular_queries_button': '📊 Популярные запросы',
        'change_language_button': '🌐 Изменить язык',
    },
    'de': {
        'greeting': "👋 Hallo, {user_name}! Ich bin ein Film-Suchbot. Wählen Sie eine Aktion:",
        'random_movie': "🎥 *Zufälliger Film:* `{movie}`",
        'actor_search': "🎭 *Filme mit {actor_name}:* \n{movies}",
        'genre_search': "🎭 *Filme des Genres {genre_name}:* \n{movies}",
        'year_search': "📅 *Filme aus dem Jahr {year}:* \n{movies}",
        'popular_queries': "📊 *Beliebte Anfragen:* \n{queries}",
        'enter_actor_name': "✍ Geben Sie den Namen des Schauspielers ein, um zu suchen:",
        'enter_genre_name': "✍ Geben Sie das Genre ein, um zu suchen:",
        'enter_year': "✍ Geben Sie das Jahr ein, um zu suchen:",
        'error': "🚨 Fehler beim Verbinden mit der Datenbank.",
        'no_results': "😔 Keine Ergebnisse gefunden.",
        'random_movie_button': '🎲 Zufälliger Film',
        'search_actor_button': '🔎 Suche nach Schauspieler',
        'search_genre_button': '🎭 Suche nach Genre',
        'search_year_button': '📅 Suche nach Jahr',
        'popular_queries_button': '📊 Beliebte Anfragen',
        'change_language_button': '🌐 Sprache ändern',
    }
}


